# Конфигурация для анализа графиков и генерации отчётов

# Настройки API для получения данных
api:
  provider: yfinance  # yfinance, binance, alpha_vantage
  api_key: ""  # API ключ (если требуется)
  api_secret: ""  # API секрет (если требуется)
  rate_limit: 1.0  # Задержка между запросами в секундах

# Настройки графиков
charts:
  width: 1200  # Ширина графика в пикселях
  height: 800  # Высота графика в пикселях
  dpi: 100  # Разрешение графика
  style: darkgrid  # Стиль графика (darkgrid, whitegrid, dark, white, ticks)
  
  # Настройки индикаторов
  indicators:
    sma: [20, 50, 200]  # Периоды для простых скользящих средних
    ema: [12, 26]  # Периоды для экспоненциальных скользящих средних
    rsi: 14  # Период для RSI
    macd: [12, 26, 9]  # Параметры MACD [быстрая, медленная, сигнальная]
    bollinger: [20, 2]  # Параметры полос Боллинджера [период, стандартные отклонения]
    volume: true  # Показывать график объёма

# Настройки анализа паттернов
patterns:
  # Анализ пробоев
  breakout:
    enabled: true
    lookback_periods: 20  # Период для поиска локальных экстремумов
    volume_threshold: 1.5  # Минимальный множитель среднего объёма
  
  # Анализ дивергенций
  divergence:
    enabled: true
    rsi_periods: 14  # Период для RSI при анализе дивергенций
    min_divergence_strength: 0.3  # Минимальная сила дивергенции
  
  # Анализ поддержки и сопротивления
  support_resistance:
    enabled: true
    min_touches: 2  # Минимальное количество касаний уровня
    tolerance: 0.02  # Толерантность для кластеризации уровней (2%)

# Настройки отчётов
reports:
  format: html  # Формат отчётов (html, pdf, markdown)
  include_charts: true  # Включать графики в отчёты
  include_indicators: true  # Включать индикаторы в отчёты
  include_patterns: true  # Включать паттерны в отчёты

# Настройки вывода
output:
  charts_dir: charts  # Директория для сохранения графиков
  reports_dir: reports  # Директория для сохранения отчётов
  screenshots_dir: screenshots  # Директория для снимков экрана
  data_dir: data  # Директория для сохранения данных
